/**
 * @author Shane
 */

var fashion = {
  hat: ['fedora', '#texture# hat', 'bandana', 'scrum cap', 'hood'],
  neck: ['scarf', 'necktie', 'choker', 'cravat', '#collar#'],
  collar: ['#texture# collar', '#fabric# neck brace', '#metal# necklace'],
  metal: ['gold', 'tin', 'foil', 'silver', 'neon', 'rust'],
  texture: ['pointy', 'stiff', 'starched', 'floppy', 'creased', 'perforated'],
  shirt: [
    'sweater',
    'hoodie',
    'blouse',
    'tee',
    'vest',
    'shirt',
    'chainmail',
    'armour',
    'tanktop',
    'sweater',
    'cape',
  ],
  coat: [
    '#texture# blazer',
    '#fabric# jacket',
    '#fabric# coat',
    'kimono',
    'ponhco',
    '#colors# raincoat',
  ],
  belt: ['#fabric# belt', 'rope'],
  pants: [
    'riding pants',
    'sweatpants',
    'jeans',
    '#skirt#',
    'trunks',
    'leggings',
  ],
  skirt: ['maxi-dress', 'mini-skirt', 'pencil-skirt', 'sun-dress'],
  socks: ['#patterns# socks'],
  shoes: [
    'pumps',
    'saddle shoes',
    'high heels',
    'slip-ons',
    'street socks',
    'dunks',
    'plim soles',
  ],
  lengths: ['short', 'medium', 'long'],
  fit: ['loose', 'tight', 'slinky', 'baggy'],
  region: ['waistlines', 'necklines', 'sleeves', 'skirts', 'beards'],
  repeat: ['#[repeat:#region#]'],
  patterns: [
    'polka dot',
    'paisley',
    'tie-die',
    'stripes',
    'herringbone',
    'checked',
    'camouflage',
    'comicstrip',
    'pointillist',
    'print',
  ],
  fabric: [
    'poplin',
    'cotton',
    'leather',
    'silk',
    'chifon',
    'wool',
    'plastic',
    'camelhair',
    'mink',
  ],
  detail: [
    'zip',
    'gloves',
    'cufflinks',
    'pockets',
    'vents',
    'pleats',
    'edging',
    'stitching',
    'trimmings',
    'effects',
    'affect',
  ],
  adj: [
    'chic',
    'ugly',
    'autumnal',
    'fashionable',
    'understated',
    'sophisticated',
    'distinguished',
    'distinct',
  ],
  sos: ['so', 'sooo', 'so, oh,', 'so so', '', '', '', ''],
  french: ['<i>au fait</i>', '<i>a la mode</i>', '<i>tres chic</i>'],
  verbs: ['wear', 'sport', 'don', 'attempt'],
  order: [
    "<strong>Don't</strong>",
    '<strong>Do it</strong>',
    'Reconsider',
    'Change course',
    'Seek advice',
    'Ask your #person#',
  ],
  order_start: [
    "<i>Don't</i>",
    '<i>Do</i>',
    '<i>Please</i>',
    "<i>It's #judge# to</i>",
    "It's #french# to",
    "In the #lengths#-term, it's best to",
  ],
  ordering: ['first', 'last', 'next'],
  judge: ['weird', '#sos# you', 'oddly fitting'],
  binaries: ['wrong', 'right'],
  relations: [
    'matching',
    'clashing',
    'coordinating',
    'contrasting',
    'balancing',
  ],
  locations: [
    'the promenade',
    'the club',
    'the alley',
    'company',
    'plain sight',
    'the crowds of onlookers',
    'the place',
    '#metal#',
    'expensive stuff',
    'formal wear',
    'New York',
    'Paris',
    'Dublin',
    'Milan',
  ],
  trends: [
    'New Sincerity',
    'New Pretty',
    'Luxe Utility',
    'vaporwave',
    'normcore',
    'romantic',
    'boho',
    'youthful',
    'cyberpunk',
    'business casual',
    'sport luxe',
    'body positive',
    'post-colonial',
    'post-modern',
    'liminal',
  ],
  forecasts: [
    'growing',
    'declining',
    'stagnating',
    'reversing',
    'plateauing',
    'going nowhere',
  ],
  transform: [
    'slimming',
    'de-aging',
    'invigorating',
    'transformational',
    'subversive',
    'transcendant',
    'life-changing',
  ],
  person: [
    'friend',
    'enemy',
    'mother',
    'father',
    'ex',
    'crush',
    'boss',
    'inner child',
    'customer',
    'avatar',
  ],
  activity: ['walking', 'swanning', 'strolling', 'swaying', 'showing off and'],
  thinking: [
    'pondering',
    'considering',
    'envisioning',
    'eyeing',
    'slipping into',
  ],
  objects: ['vases', 'fruits', 'flowers', 'tragedies'],
  colors: [
    'blue',
    'Pernod yellow',
    'hot pink',
    'beige',
    'sepia',
    'pale orange',
    'sunwashed',
    'electric blue',
    'jet black',
    'dyed black',
    'tan',
  ],
  status: [
    '<i>in</i>',
    '<i>out</i>',
    '<i>over</i>',
    '<i>done</i>',
    '<i>finished</i>',
    '<i>embarassing</i>',
    '<i>dead</i>',
    '#era#',
    'coming <i>back</i>',
  ],
  era: [
    'great depression',
    'cold war',
    'tv dinner',
    'last #seasons#',
    'next #seasons#',
  ],
  seasons: [
    'Spring',
    'Summer',
    'Autumn',
    'Winter',
    'Springtime',
    'Summertime',
    'Fall',
    'Christmas',
    'Oscar season',
    'red carpet season',
    'Grammy awards',
    'prom',
    'NFL draft',
  ],
  times: [
    'morning',
    'midday',
    'lunchtime',
    'evening',
    "five o'clock",
    'weekend',
    'Saturday night',
    'Sunday morning',
  ],
  event: [
    'journey',
    'apology',
    'liason',
    'indiscretion',
    'trip',
    '#times# party',
    '#times# dance',
    '#times# ritual',
  ],
  group: [
    'ensemble',
    'collection',
    'combination',
    'one-piece',
    'outfit',
    'look',
  ],
  ambigs: ['for now', 'one imagines', 'it is said', 'for some', 'last year'],
  random: [
    'horns',
    'masks',
    'discomfort',
    'flares',
    'novelty hats',
    'joke t-shirts',
  ],
  vibes: ['vibes', 'morals', 'expectations', 'poses', 'interactions'],
  vibes2: [
    'vibes',
    'do it',
    'breathe',
    'exhale',
    'pose',
    'pay rent',
    'do taxes',
    'skip the meeting',
    'just <i>be</i>',
    'just go',
  ],
  sig: [
    'signature',
    'statement',
    'f@*k you',
    'passive-aggressive',
    'just-out-of-bed',
    'I-woke-up-in-this',
    'oh-this-old-thing',
  ],
  punctuate: [',', ',', ':'],
  thing: ['thing'],
  digit1: ['', '1', '2', '3', '4', '5'],
  digit2: ['2', '3', '4', '5'],
  line: [
    'When #activity# in #locations#, #verbs# a #colors# #hat# with #relations# #shirt#',
    '#colors.capitalize# is #sos# #status#',
    'Fashion is #era##punctuate# #status#.',
    'If #thinking# a #colors# #patterns# #skirt#: #order#.',
    "It's #era#, #colors# and #objects#",
    '#french#, all #metal#',
    '#order_start# be caught #activity# in a #trends# #group#.',
    'That #group# makes sense . . . #ambigs#',
    'Dress like your #person#',
    'With #person#, think #random#',
    '#digit1##digit2# things #binaries# about your outfit',
    '#digit1##digit2# reasons you dress like your #person#',
    'The #digit1##digit2# elements to any #seasons# #group#',
    '#digit2# #thing.s# #binaries# about #fabric#',
    'That might make sense on a #digit2##digit2# year old',
    'Where a #hat# is #texture# the #shirt# should be #texture# with a #lengths# collar',
    'Remember: #relations# is to #transform# as #shoes# are to #adj#',
    'This #times#, pair #colors# coat with signature #detail#',
    "It's #metal# #detail# for the #event#",
    'We can see #patterns# #texture# #pants# coming back',
    "It's always #fit# #shirt# and #fit# #vibes#",
    'Just now... #fabric# with #colors# #patterns# on #colors# background and #metal# #detail#.',
    'The #patterns# #neck# gives an air of the #trends#',
    'For the #event#, a #fit# #fabric# #skirt# will be #transform#',
    'The fashion for #shoes# is #forecasts#',
    'A period of long #repeat# will necessarily be followed by a period of short #repeat#',
  ],
  pronouncement: ['#line#'],
  origin: '#pronouncement#',
}

var philosophy = {
  begin: ['becoming', 'towards', 'being', 'understanding', "why I'm"],
  looking: ['seeking', 'finding', 'exploring', 'critiquing', 'overview of'],
  things: [
    '<i>noumenon</i>',
    'society',
    'psychology',
    'embodiment',
    'artificial intelligence',
    'textuality',
    'x',
    'number',
    'boundaries',
    'a given thing',
    'this thing right here',
    'nothing',
    'anything',
    'an article',
  ],
  pluralities: [
    'people',
    'atoms',
    'particles',
    'entities',
    'spirits',
    'philosophers',
    'citizens',
    'bits',
    'figments',
  ],
  mundanes: [
    'afternoon nap',
    'sporting event',
    'SUV',
    'headache',
    'website',
    'philosopher',
    'thing itself',
    'biscuit',
    '#worker# #workthing#',
    'sandwich',
  ],
  worker: [
    "scientist's",
    "philosopher's",
    "tradesman's",
    "office worker's",
    "artist's",
    "metaphysician's",
    "epistemologist's",
    "ethicist's",
    "idle person's",
  ],
  workthing: [
    'happiness',
    'ethic',
    'tools',
    'sadness',
    'reveries',
    'suffering',
    'knowing <i>that</i>',
    'knowing <i>how</i>',
    'knowing <i>why</i>',
  ],
  place: [
    'wasteland',
    'graveyard',
    'void',
    'threshold',
    'edge',
    'mall',
    'roller rink',
    'tattoo shop',
    'drive-through',
    'interface',
  ],
  account: [
    'mereological',
    'topological',
    'teleological',
    'novel',
    'first',
    'participatory',
    'first-hand',
    'definitive',
    'collaborative',
  ],
  prefix_1: ['pre', 'post'],
  prefix_2: ['post', 'quasi', 'faux', 'neo', 'liminal', 'meta'],
  prefix_3: ['#prefix_2#'],
  prefix_4: [
    'hetero-',
    'shizo-',
    'spatio-',
    'gyno-',
    'logo-',
    'phallo-',
    'proto-',
    'mereo-',
    'pan-',
    'crypto-',
    'anarcho-',
    'cyber-',
    'poly-',
    'mono-',
    'trans-',
    'inter-',
    'pro-',
    'anti-',
  ],
  death: [
    'imperial',
    'descriptive',
    'causal',
    'cultural',
    'topological',
    'universalist',
    'normative',
    'globalist',
    'normal',
    'logical',
    'marxist',
    'modern',
    'feudalist',
    'punk',
    'fetishistic',
    'structuralist',
    'industrial',
    'capitalist',
    'Taylorist',
    'Deluzian',
    'pragmatist',
    'romantic',
    'futurist',
    'utopian',
    'dystopian',
  ],
  nouns: [
    'apologetics',
    'scientism',
    'athletics',
    'socialism',
    'rhizomatics',
    'consumerism',
    'liminality',
    'fatalism',
    'ontology',
    'feminism',
    'egoism',
    'Taylorism',
    'consumerism',
    'paradigm',
    'society',
    'internet',
    'philosophy',
    'axiomatics',
  ],
  paradigm: [
    'modernist',
    'phenomenologist',
    'conservative',
    'liberal',
    'positivist',
    'materialist',
    'deflationist',
    'structuralist',
    'nominalist',
    'fallabalist',
    'feminist',
    'existentialist',
  ],
  isms: [
    'modernism',
    'phenomenologism',
    'classicalism',
    'structuralism',
    'colonialism',
    'technologicalism',
    'feminism',
    'existentialism',
  ],
  era: [
    'feudal',
    'imperialist',
    'collectivist',
    'socialist',
    'capitalist',
    'enlightenment',
    'sincere',
    'pandemic',
  ],
  thinkerism: [
    'Whiteheadian',
    'Hegelian',
    'Aristotelian',
    'Platonist',
    'Heidegerrian',
    'Wittgenstenian',
    'Deluezian',
    'Lacanian',
  ],
  thinker_type: [
    'lapsed',
    'enthusiastic',
    'wayward',
    'confused',
    'analytic',
    'continental',
    'pining',
    'unfortunate',
  ],
  field: [
    '#stage# architectonics',
    'logic',
    'science',
    'design',
    'engineering',
    'philosophy',
    'metaphysics',
    'ethics',
    'epistemology',
    'aesthetics',
    'axiology',
  ],
  stage: ['new', 'late', 'better', 'lesser'],
  method: [
    'conceptual analysis',
    'deconstruction',
    'problematisation',
    'critique',
    'reevaluation',
    'grounding',
  ],
  hot_1: [
    'cyber',
    'larval',
    'oedipal',
    'gender',
    'oneric',
    'industrial',
    '<i>autotelic</i>',
    'transcendental',
    'identity',
    'solar',
    'lunar',
    'virtual',
    'alarmist',
    'meta',
    'post',
    'naive',
    'opinionated',
    'cyber',
    'fluid',
    'concrete',
    'information',
  ],
  hot_2: ['punk', 'flux', 'norms', 'anxiety', 'semiotics', 'imaginings'],
  concepts: [
    'type theory',
    'modal logic',
    'conceptual engineering',
    'panpsychism',
    'object oriented ontology',
    'nowhere',
  ],
  line: [
    '#looking# #prefix_1#-#paradigm# #pluralities#',
    '#begin# #prefix_1#-#paradigm#',
    '#hot_1# #paradigm# #isms# for the #thinker_type# #thinkerism# ',
    'the #mundanes#: a #method# ',
    '#prefix_4##death# accounts of #nouns#: a review ',
    'philosopher at the #place#: a #account# account',
    'the #worker# #workthing# in the #era# era ',
    '#hot_1# #paradigm# considers #things#',
    '#prefix_1#-#prefix_2#-#era# #isms#',
    '#isms# for #thinkerism# #method# of #field#',
    '#hot_1#-#hot_2#',
    '#hot_1#-#hot_2# and #prefix_1#-#prefix_3# #era# #isms#',
    'what is #things#? Perspectives from #concepts# ',
    'towards a #field# of #paradigm# #hot_1# #hot_2#',
  ],
  pronouncement: ['#line#'],
  origin: '#pronouncement#',
}

var food = {
  prefix_m: ['low', 'medium', 'high'],
  prefix_g: ['enriched', 'concentrated'],
  prefix_b: ['reduced', 'low'],
  component_m: ['protein', 'fat', 'carbohydrate'],
  component_g: [
    'minerals',
    'polyphenols',
    'fibre',
    'probiotics',
    'antioxidants',
  ],
  component_b: [
    '<i>trans fats</i>',
    'bacteria',
    'lactose',
    'gluten',
    'FODMAPs',
    'beta-casein',
  ],
  structure: [
    'emulsion',
    'sponge',
    'mousses',
    'gel',
    'beverage',
    'snack',
    'shake',
  ],
  value_g: ['good', 'friendly', 'clean'],
  value_b: ['bad', 'dangerous', 'artificial'],
  taste: ['sweet', 'sour', 'salty', 'umami', 'bitter'],
  flavour: ['fruity', 'clean', 'chocolatey', 'unmistakeable', ''],
  vague: ['fresh', 'natural', 'clean', 'sustainable'],
  homely: ['traditional', 'handmade', 'cutting-edge', 'gentle'],
  equipment: [
    'homogeniser',
    'pasteuriser',
    'steriliser',
    'extruder',
    'irradiator',
    'drier',
    'pressuriser',
  ],
  make: [
    'handmade',
    'lovingly crafted',
    'locally produced',
    'custom-made',
    'specially constructed',
  ],
  location: [
    'family farm',
    'pristine hedgegrow',
    'centuries-old workshop',
    'high-tech facility',
    'secret location',
    'converted bunker',
  ],
  demographic: [
    'youthful',
    'health-conscious',
    'sporty',
    'fashionable',
    'early-adopters',
    'foodies',
  ],
  genre: ['luxury', 'diet', 'convenient', 'essential'],
  sense: ['aroma', 'flavour', 'taste', 'notes'],
  line: [
    '#prefix_m#-#component_m# #structure#',
    '#prefix_g# in #value_g# #component_g#, #prefix_b# in #value_b# #component_b#',
    '#make# with our #homely# #equipment# in a #location#',
    '#prefix_m#-#component_m# and #prefix_g# in #component_g# with #flavour# #sense#',
    '#vague# #component_m# for the #demographic#',
  ],
  pronouncement: ['#line#'],
  origin: '#pronouncement#',
}

grammar.addModifiers(tracery.baseEngModifiers)
